ChildJourney/Controllers/GameController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ChildJourney.Data;
using ChildJourney.ViewModels;
using Newtonsoft.Json;
using System.Numerics;
using ChildJourney.Models;
using System;
using System.Globalization;
using System.Net;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace ChildJourney.Controllers
{
    public class GameController : Controller
    {
        private readonly Database _context;

        public GameController(Database context)
        {
            _context = context;
        }

        //Fillings Viewmodels
        public AdminViewModel AdminViewModel(Island island)
        {
            var viewModel = new AdminViewModel()
            {
                Users = _context.Users.ToList(),
                Animals = _context.Animals.ToList(),
                Badges = _context.Badges.ToList(),
                bodyParts = _context.BodyParts.ToList(),
                clothing = _context.Clothing.ToList(),
                decorations = _context.Decoration.ToList(),
                Moods = _context.Moods.ToList(),
                rewards = _context.Rewards.ToList(),
                Outfit_Clothings = _context.OutfitClothing.ToList(),
                Body_BodyParts = _context.BodyBodyParts.ToList(),
                UserBodyPart = _context.UsersBodyParts.ToList(),
                House_Decos = _context.HouseDecoration.ToList(),
                UserClothing = _context.UsersClothing.ToList(),
                UserAnimals = _context.UsersAnimals.ToList(),
                UserDecoration = _context.UsersDecorations.ToList(),
                UserBadges = _context.UsersBadges.ToList(),
                UserRewards = _context.UsersRewards.ToList(),
                Islands = _context.Islands.ToList(),
                CurrentIsland = island,
                User_Island = _context.UserIslands.ToList(),
                User = JsonConvert.DeserializeObject<User>(HttpContext.Session.GetString("CurrentUser"))
        };
            return viewModel;
        }
        public HomeController HomeController()
        {
            var Hc = new HomeController(_context);
            return Hc;
        }

        //Getting Views
        public IActionResult TimedRewards()
        {
            var response = JsonConvert.DeserializeObject<User>(HttpContext.Session.GetString("CurrentUser"));
            User user = _context.Users.Find(response.Id);
            int Rewardcount = 0;
            foreach (var Rewardpiece in _context.UsersRewards.ToList())
            {
                if (Rewardpiece.UserId == user.Id)
                {
                    Rewardcount += 1;
                }
            }
            if (Rewardcount == 0)
            {
                foreach (var Reward in _context.Rewards.ToList())
                {
                    AddReward(Reward, user);
                }
            }
            return View(HomeController().AdminViewModel());
        }
        public IActionResult Character()
        {
            var response = JsonConvert.DeserializeObject<User>(HttpContext.Session.GetString("CurrentUser"));
            User user = _context.Users.Find(response.Id);
            int Clothingcount = 0;
            int Bodypartcount = 0;
            int Islandcount = 0;
            int Decorationcount = 0;
            foreach (var clothingpiece in _context.UsersClothing.ToList())
            {
                if (clothingpiece.UserId == user.Id) 
                {
                    Clothingcount += 1;
                }
            }
            foreach (var Bodypart in _context.UsersBodyParts.ToList())
            {
                if (Bodypart.UserId == user.Id)
                {
                    Bodypartcount += 1;
                }
            }
            foreach (var Island in _context.UserIslands.ToList())
            {
                if (Island.UserId == user.Id)
                {
                    Islandcount += 1;
                }
            }
            foreach (var Decorationpiece in _context.UsersDecorations.ToList())
            {
                if (Decorationpiece.UserId == user.Id)
                {
                    Decorationcount += 1;
                }
            }
            if (Clothingcount == 0)
            {
                foreach(var Clothing in _context.Clothing.ToList())
                {
                    if (Clothing.Price == 0) 
                    { 
                        AddClothing(Clothing, user);
                    }
                }
            }
            if (Bodypartcount == 0)
            {
                foreach (var Bodypart in _context.BodyParts.ToList())
                {
                    if (Bodypart.Price == 0)
                    {
                        AddBodyPart(Bodypart, user);
                    }
                }
            }
            if (Islandcount == 0)
            {
                foreach (var Island in _context.Islands.ToList())
                {
                    if (Island.Price == 0)
                    {
                        AddIsland(Island, user);
                    }
                }
            }
            if (Decorationcount == 0)
            {
                foreach (var Deco in _context.Decoration.ToList())
                {
                    if (Deco.Price == 0)
                    {
                        AddDecoration(Deco, user);
                    }
                }
            }
            return View(HomeController().AdminViewModel());
        }
        public IActionResult Islandpicking()
        {
            return View(HomeController().AdminViewModel());
        }
        public IActionResult Inventory(int? Id)
        {
            Island island;
            if (Id == null)
            {
                Island response = JsonConvert.DeserializeObject<Island>(HttpContext.Session.GetString("CurrentIsland"));
                island = response as Island;
            }
            else { island = _context.Islands.Find(Id); }

            return View(AdminViewModel(island));
        }
        public IActionResult StoreBodyPart(int? Id)
        {
            Island island;
            if (Id == null)
            {
                Island response = JsonConvert.DeserializeObject<Island>(HttpContext.Session.GetString("CurrentIsland"));
                island = response as Island;
            }
            else { island = _context.Islands.Find(Id); }

            return View(AdminViewModel(island));
        }
        public IActionResult StoreClothing(int? Id)
        {
            Island island;
            if (Id == null)
            {
                Island response = JsonConvert.DeserializeObject<Island>(HttpContext.Session.GetString("CurrentIsland"));
                island = response as Island;
            }
            else { island = _context.Islands.Find(Id); }

            return View(AdminViewModel(island));
        }
        public IActionResult StoreIslands(int? Id)
        {
            Island island;
            if (Id == null)
            {
                Island response = JsonConvert.DeserializeObject<Island>(HttpContext.Session.GetString("CurrentIsland"));
                island = response as Island;
            }
            else { island = _context.Islands.Find(Id); }

            return View(AdminViewModel(island));
        }
        public IActionResult StoreDecorations(int? Id)
        {
            Island island;
            if (Id == null)
            {
                Island response = JsonConvert.DeserializeObject<Island>(HttpContext.Session.GetString("CurrentIsland"));
                island = response as Island;
            }
            else { island = _context.Islands.Find(Id); }

            return View(AdminViewModel(island));
        }
        public IActionResult HomeIsland(int? Id)
        {
            Island island;
            if (Id == null)
            {
                Island islandresponse = JsonConvert.DeserializeObject<Island>(HttpContext.Session.GetString("CurrentIsland"));
                island = islandresponse as Island;
            }
            else
            {
                island = _context.Islands.Find(Id);
                var islandJson = JsonConvert.SerializeObject(island);
                HttpContext.Session.SetString("CurrentIsland", islandJson);
            }

            var response = JsonConvert.DeserializeObject<User>(HttpContext.Session.GetString("CurrentUser"));
            User user = _context.Users.Find(response.Id);
            int Day;

            using (var client = new HttpClient())
            {
                DayOfWeek Result;
                
                try
                {
                    var result = client.GetAsync("https://google.com", HttpCompletionOption.ResponseHeadersRead).Result;
                    Result = result.Headers.Date.Value.DayOfWeek;
                    Day = result.Headers.Date.Value.Day;
                }
                catch {
                    Result = DateTime.Today.DayOfWeek;
                    Day = DateTime.Today.Day;
                }
                if (user.lastMonthLogin != Day && user.Daystreak != (int)Result)
                {
                    user.DailyStreak = 0;
                    _context.SaveChanges();
                }                
                user.lastWeekLogin = user.Daystreak;
                user.Daystreak = (int)Result;
            }

            if (user.Daystreak != user.lastWeekLogin)
            {
                int counter = 0;
                foreach (var item in _context.UsersRewards.ToList())
                {
                    if (item.Type == "WeeklyClaimed" && item.UserId == user.Id)
                    {
                        counter += 1;
                    }
                    if (response.Daystreak < _context.Rewards.Find(item.RewardId).Day && item.Type == "WeeklyClaimed" && item.UserId == response.Id)

ChildJourney/Views/Game/HomeIsland.cshtml
@model ChildJourney.ViewModels.AdminViewModel
@using Newtonsoft.Json
@{
    ViewData["Title"] = "HomeIsland";
    Context.Session.SetString("HomeIsland", "Active");
    User user = null;
    bool PrintMoodpicker = true;
    int Result;
    foreach(var User in Model.Users)
    {
        if (User.Id == Model.User.Id)
        {
            user = User;
        }
    }
    using (var client = new HttpClient())
    {
        try
        {
            var result = client.GetAsync("https://google.com", HttpCompletionOption.ResponseHeadersRead).Result;
            Result = result.Headers.Date.Value.Day;
        }
        catch
        {
            Result = DateTime.Today.Day;
        }
    }
    foreach (var Mood in Model.Moods)
        {
            if (Mood.Day == Result && Mood.UserId == user.Id)
            {
                PrintMoodpicker = false;
            }
        }
}

<style>
    .container {
        position: relative;
    }

    .house {
        position: relative;
        width: 100px;
        margin: 100px auto;
        transform-style: preserve-3d;
        transform: rotateX(-40deg) rotateY(45deg);
    }
    .store {
        position: absolute;
        top: 100px;
        width: 100px;
        margin: 100px auto;
        transform-style: preserve-3d;
        transform: rotateX(-40deg) rotateY(45deg);
    }
    .face {
        position: absolute;
        width: 100px;
        height: 100px;
        background: #8c6b5c;
        border: 1px solid #614537;
    }
    .door {
        position: absolute;
        width: 30px;
        height: 70px;
        background: lightblue;
        border: 1px solid #614537;
    }
</style>

<style>
    html,body {
        margin: 0;
        min-height: 100%;
        width: 100%;
    }
    a {
        text-decoration:none;
        color:black;
    }
</style>

@if (PrintMoodpicker == true)
{
    <div class="button" style="position:fixed;bottom:10px;left:120px">
        <label>How are you feeling today?</label>
        <select style="border-radius: 15px; background-color: rgba(255, 255, 255, 0.5); padding:5px;" onchange="AddMood(this.value, @Model.User.Id, @Result)">
            <option></option>
            <option value="😞">Very Sad</option>
            <option value="🙁">Sad</option>
            <option value="🙂">Okay</option>
            <option value="😀">Happy</option>
            <option value="😄">Very Happy</option>
        </select>
    </div>
}
<body style="background-color: @Model.CurrentIsland.PrimaryColor;">
    <a asp-action="TimedRewards" asp-controller="Game" class="button" style="position:fixed;left:10px; top:10px">Rewards</a>
    <a asp-action="IslandPicking" asp-controller="Game" class="button" style="position:fixed;left:110px; top:10px">Islands</a>
    <a asp-action="Inventory" asp-controller="Game" class="button" style="position:fixed;left:10px; bottom:10px;">Inventory</a>
    
    <a asp-action="PlayGame" asp-controller="Home" class="button" style="position:fixed;left:198px; top:10px">Quit</a>
    <div style="position:fixed;right:10px; top:10px">
        <div class="button">
            <H5><img src="/images/Coin.png" style="width:20px; height:20px" /> @user.Coins </H5>
            <label> @user.SeasonPoints SeasonPoints</label>
        </div>
        <div class="button" style="margin-top:10px">
            <label>@user.DailyStreak /3 Daily rewards claimed!</label>
        </div>
        <div class="button" style="margin-top:10px">
            <H5>Timed Moves tasks</H5>
            <p>- <a asp-action="BoatSteering" asp-controller="MiniGames">BoatSteering</a></p>
            <p>- <a asp-action="AnimalCatch" asp-controller="MiniGames">Animalcatch</a></p>
        </div>
        <div class="button" style="margin-top:10px">
            <H5>Repeating Moves tasks</H5>
            <p>- <a asp-action="BirdFlying" asp-controller="MiniGames">BirdFlying</a></p>
        </div>
    </div>
    
    <div class="container">
        <div class="house">
            <a asp-action="Character" asp-controller="Game" style="background-color:white ;border:solid; color: black; text-decoration: none">Home</a>
            <div class="face" style="transform: translateZ(50px)"></div>
            <div class="door" style="transform: translateX(-16px) rotateY(-90deg) translateY(29px);"></div>
            <div class="face" style="transform: translateX(-50px) rotateY(-90deg)"></div>
            <div class="face" style="transform: translateY(-50px) rotateX(90deg)"></div>
        </div>

        <div class="store">
            <a asp-action="StoreBodyPart" asp-controller="Game" style="background-color:white ;border:solid; color: black; text-decoration: none">Store</a>
            <div class="face" style="transform: translateZ(50px)"></div>
            <div class="door" style="transform: translateY(20px) rotateY(180deg) translateX(-29px) translateZ(-58px);"></div>
            <div class="face" style="transform: translateX(-50px) rotateY(-90deg)"></div>
            <div class="face" style="transform: translateY(-50px) rotateX(90deg)"></div>
        </div>
    </div>
</body>
    

ChildJourney/Views/Game/Introduction.cshtml
@model ChildJourney.ViewModels.AdminViewModel
@using ChildJourney.Controllers;
@using Newtonsoft.Json
@{
    ViewData["Title"] = "Introduction";
    User response = JsonConvert.DeserializeObject<User>(Context.Session.GetString("CurrentUser"));
    foreach (var user in Model.Users)
    {
        if (user.Id == response.Id)
        {
            response = user;
        }
    }
}

<style>
    body {
        background-image: url("");
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover;
    }
</style>

<div class="row">
    <div class="block">
        <h1>Create Your Character!</h1>
    </div>
</div>
<div class="row">
    <div class="block">
        <button id="1" onclick="menupicker(this.id)">Eyes</button>
    </div>
    <div class="block">
        <button id="2" onclick="menupicker(this.id)">Mouth</button>
    </div>
    <div class="block">
        <button id="3" onclick="menupicker(this.id)">Hair</button>
    </div>
    <div class="block">
        <button id="4" onclick="menupicker(this.id)">Body</button>
    </div>
    <div class="block">
        <button id="5" onclick="menupicker(this.id)">Hat</button>
    </div>
    <div class="block">
        <button id="6" onclick="menupicker(this.id)">Shirt</button>
    </div>
    <div class="block">
        <button id="7" onclick="menupicker(this.id)">Pants</button>
    </div>
    <div class="block">
        <button id="8" onclick="menupicker(this.id)">Outfit</button>
    </div>
    <div class="block">

        @{
            List<BodyBodyParts> bodycheck = new List<BodyBodyParts>();
            List<Outfit_Clothing> Clothingcheck = new List<Outfit_Clothing>();
            foreach (var item in Model.Body_BodyParts)
            {
                if (response.BodyId == item.BodyId)
                {
                    bodycheck.Add(item);
                }
            }
            foreach (var item in Model.Outfit_Clothings)
            {
                if (response.OutfitId == item.OutfitId)
                {
                    Clothingcheck.Add(item);
                }
            }
            if (Clothingcheck.Count == 3 && bodycheck.Count == 3)
            {
                <button><a asp-action="Islandpicking" asp-controller="Game">Confirm</a></button>
            }

         }
    </div>
    </div>
</div>
<div class="row"></div>
    <div Id="pickwrapper1" class="container-fluid" style="display:none;">
        <div class="row">
            <div class="inner" style="border-radius: 25px; border-color:lightgray">
                <label id="Dwindow">Hello there @response.Name, Are you new here?1</label>
            </div>
            <div style="height:500px">
                @foreach (var item in Model.bodyParts)
                {

                    if (item.Type == "Eyes")
                    {
                        <div style="display:inline-block ; width:130px ; margin:0 0 30px 0; background-color:white">
                            <button onclick="AddToBody('@item.Id')">
                                <table class="table">
                                    <tr>
                                        <td><img src="@item.Image" style="width:100px; height:100px;" align="center" /></td>
                                    </tr>
                                    <tr>
                                        <td><label align="center"> @item.Name @item.Type</label></td>
                                    </tr>
                                </table>
                            </button>
                        </div>
                    }

                }
            </div>
        </div>
    </div>
    <div Id="pickwrapper2" class="container-fluid" style="display:none;">
        <div class="row">
            <div class="inner" style="border-radius: 25px; border-color:lightgray">
                <label id="Dwindow">Hello there @response.Name, Are you new here?2</label>
            </div>
            <div style="height:500px">
                @foreach (var item in Model.bodyParts)
                {
                    if (item.Type == "Mouth")
                    {
                        <div style="display:inline-block ; width:130px ; margin:0 0 30px 0; background-color:white">
                            <button onclick="AddToBody('@item.Id')">
                                <table class="table">
                                    <tr>
                                        <td><img src="@item.Image" style="width:100px; height:100px;" align="center" /></td>
                                    </tr>
                                    <tr>
                                        <td><label align="center"> @item.Name @item.Type</label></td>
                                    </tr>
                                </table>
                            </button>
                        </div>
                    }
                }
            </div>
        </div>
    </div>
    <div Id="pickwrapper3" class="container-fluid" style="display:none;">
        <div class="row">
            <div class="inner" style="border-radius: 25px; border-color:lightgray">
                <label id="Dwindow">Hello there @response.Name, Are you new here?3</label>
            </div>
            <div style="height:500px">
                @foreach (var item in Model.bodyParts)
                {
                    if (item.Type == "Hair")
                    {
                        <div style="display:inline-block ; width:130px ; margin:0 0 30px 0; background-color:white">
                            <button onclick="AddToBody('@item.Id')">
                                <table class="table">
                                    <tr>
                                        <td><img src="@item.Image" style="width:100px; height:100px;" align="center" /></td>
                                    </tr>
                                    <tr>
                                        <td><label align="center"> @item.Name @item.Type</label></td>
                                    </tr>
                                </table>
                            </button>
                        </div>
                    }
                }
            </div>
        </div>
    </div>
    <div Id="pickwrapper4" class="container-fluid" style="display:none;">
        <div class="row">
            <div class="inner" style="border-radius: 25px; border-color:lightgray">
            <label id="Dwindow"> Selected bodypieces @bodycheck.Count out of 3!</label>
            </div>
            <div style="height:500px">
                @foreach (var item in Model.Body_BodyParts)
                {
                    if (response.BodyId != null)
                    {
                        if (item.BodyId == response.BodyId)
                        {
                            <div style="display:inline-block ; width:130px ; margin:0 0 30px 0; background-color:white">
                                <table class="table">
                                    <tr>
                                        <td><img src="@item.BodyPart.Image" style="width:100px; height:100px;" align="center" /></td>
                                    </tr>
                                    <tr>
                                        <td><label align="center"> @item.BodyPart.Name @item.BodyPart.Type</label></td>
                                    </tr>
                                </table>
                            </div>
                        }
                    }
                }
            </div>
        </div>
    </div>
    <div Id="pickwrapper5" class="container-fluid" style="display:none;">
        <div class="row">
            <div class="inner" style="border-radius: 25px; border-color:lightgray">
                <label id="Dwindow">Hello there @response.Name, Are you new here?5</label>
            </div>
            <div style="height:500px">
                @foreach (var item in Model.clothing)
                {
                    if (item.Type == "Hat")
                    {
                        <div style="display:inline-block ; width:130px ; margin:0 0 30px 0; background-color:white">
                            <button onclick="AddToOutfit('@item.Id')">
                                <table class="table">
                                    <tr>
                                        <td><img src="@item.Image" style="width:100px; height:100px;" align="center" /></td>
                                    </tr>
                                    <tr>
                                        <td><label align="center"> @item.Name @item.Type</label></td>
                                    </tr>
                                </table>
                            </button>
                        </div>
                    }
                }
            </div>
        </div>
    </div>
    <div Id="pickwrapper6" class="container-fluid" style="display:none;">
        <div class="row">
            <div class="inner" style="border-radius: 25px; border-color:lightgray">
                <label id="Dwindow">Hello there @response.Name, Are you new here?6</label>
            </div>
            <div style="height:500px">
                @foreach (var item in Model.clothing)
                {
                    if (item.Type == "Shirt")
                    {
                        <div style="display:inline-block ; width:130px ; margin:0 0 30px 0; background-color:white">
                            <button onclick="AddToOutfit('@item.Id')">
                                <table class="table">
                                    <tr>
                                        <td><img src="@item.Image" style="width:100px; height:100px;" align="center" /></td>
                                    </tr>
                                    <tr>
                                        <td><label align="center"> @item.Name @item.Type</label></td>
                                    </tr>
                                </table>
                            </button>
                        </div>
                    }
                }
            </div>
        </div>
    </div>
    <div Id="pickwrapper7" class="container-fluid" style="display:none;">
        <div class="row">
            <div class="inner" style="border-radius: 25px; border-color:lightgray">
                <label id="Dwindow">Hello there @response.Name, Are you new here?7</label>
            </div>
            <div style="height:500px">
                @foreach (var item in Model.clothing)
                {
                    if (item.Type == "Pants")
                    {
                        <div style="display:inline-block ; width:130px ; margin:0 0 30px 0; background-color:white">
                            <button onclick="AddToOutfit('@item.Id')">
                                <table class="table">
                                    <tr>
                                        <td><img src="@item.Image" style="width:100px; height:100px;" align="center" /></td>
                                    </tr>
                                    <tr>
                                        <td><label align="center"> @item.Name @item.Type</label></td>
                                    </tr>
                                </table>
                            </button>
                        </div>
                    }
                }
            </div>
        </div>
    </div>
    <div Id="pickwrapper8" class="container-fluid" style="display:none;">
        <div class="row">
            <div class="inner" style="border-radius: 25px; border-color:lightgray">
            <label>Selected clothingpieces @Clothingcheck.Count out of 3!</label>
            </div>
            <div style="height:500px">
                @foreach (var item in Model.Outfit_Clothings)
                {
                    if (response.OutfitId != null)
                    {
                        if (item.OutfitId == response.OutfitId)
                        {
                            <div style="display:inline-block ; width:130px ; margin:0 0 30px 0; background-color:white">
                                <table class="table">
                                    <tr>
                                        <td><img src="@item.Clothing.Image" style="width:100px; height:100px;" align="center" /></td>
                                    </tr>
                                    <tr>
                                        <td><label align="center"> @item.Clothing.Name @item.Clothing.Type</label></td>
                                    </tr>
                                </table>
                            </div>
                        }
                    }
                }
            </div>
        </div>
    </div>
</div>

<script>
    function menupicker(ButtonId) {
        document.getElementById("pickwrapper1").style.display = "none";
        document.getElementById("pickwrapper2").style.display = "none";
        document.getElementById("pickwrapper3").style.display = "none";
        document.getElementById("pickwrapper4").style.display = "none";
        document.getElementById("pickwrapper5").style.display = "none";
        document.getElementById("pickwrapper6").style.display = "none";
        document.getElementById("pickwrapper7").style.display = "none";
        document.getElementById("pickwrapper8").style.display = "none";
        document.getElementById("pickwrapper" + ButtonId).style.display = "block";
    }
</script>

ChildJourney/Views/Game/Islandpicking.cshtml
@using ChildJourney.Controllers;
@using Newtonsoft.Json
@model ChildJourney.ViewModels.AdminViewModel
@{
    ViewData["Title"] = "Introduction";
    User response = JsonConvert.DeserializeObject<User>(Context.Session.GetString("CurrentUser"));
    Context.Session.SetString("HomeIsland", "InActive");
}

<style>
    ::-webkit-scrollbar{
        display:none;
    }

    body {
        background-image: url("../images/cloudybackground.png");
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover;
    }
</style>

<body style="overflow:hidden">
    <div class="row">
        <div class="block">
            <h1 class="blurry" style="padding:15px;margin-top:20px">Pick an Island!</h1>
        </div>
    </div>
    <div class="row">
        <div class="center-container" onWheel="this.scrollLeft+=event.deltaY>0?50:-50" style="justify-content:start; overflow-x:scroll; width:auto">
            @foreach (var Island in Model.Islands)
            {
                @foreach (var item in Model.User_Island)
                {
                    if (item.UserId == response.Id && item.IslandId == Island.Id) {
                        <a asp-action="HomeIsland" asp-controller="Game" asp-route-id="@item.IslandId" style="color: black; text-decoration: none">
                            <div style="padding:15px; margin:0px 30px 0px 30px" class="blurry">
                                <table>
                                    <tr>
                                    <td>
                                        <label style="background-color:@item.Island.PrimaryColor;">@Island.Id: @Island.Name</label>
                                    </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <img src="@Island.Image" style="width:250px; height:250px;" />
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </a>
                    }
                }
            }
        </div>
    </div>
</body>